-- =============================================================
-- 201_storage_assets_i18n.sql
-- Bereket Fide - Storage Assets i18n (for future multi-language support)
-- ✅ Includes inventory seed package image i18n rows
-- ✅ Additional translations can be added here when needed
-- =============================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET FOREIGN_KEY_CHECKS = 0;

START TRANSACTION;

-- -------------------------------------------------------------
-- TABLE GUARD
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `storage_assets_i18n` (
  id              CHAR(36)      NOT NULL,
  asset_id        CHAR(36)      NOT NULL,
  locale          VARCHAR(8)    NOT NULL,

  name            VARCHAR(255)  DEFAULT NULL,
  alt             VARCHAR(255)  DEFAULT NULL,
  caption         TEXT          DEFAULT NULL,
  description     TEXT          DEFAULT NULL,

  created_at      DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at      DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (id),
  UNIQUE KEY uniq_asset_locale (asset_id, locale),
  KEY idx_storage_i18n_locale (locale),
  CONSTRAINT fk_storage_i18n_asset
    FOREIGN KEY (asset_id)
    REFERENCES storage_assets(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- Seed data below is idempotent
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- INVENTORY SEED PACKAGE IMAGE I18N
-- -------------------------------------------------------------
INSERT INTO `storage_assets_i18n`
(`id`, `asset_id`, `locale`, `name`, `alt`, `caption`, `description`, `created_at`, `updated_at`)
VALUES
  ('bf-inv-seed-tr-0001', 'bf-inv-seed-img-0001', 'tr', 'Envanter tohum paketi 01 arka yüz', 'Bereket Fide envanter tohum paketi 01 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 01 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0002', 'bf-inv-seed-img-0002', 'tr', 'Envanter tohum paketi 01 ön yüz', 'Bereket Fide envanter tohum paketi 01 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 01 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0003', 'bf-inv-seed-img-0003', 'tr', 'Envanter tohum paketi 02 arka yüz', 'Bereket Fide envanter tohum paketi 02 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 02 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0004', 'bf-inv-seed-img-0004', 'tr', 'Envanter tohum paketi 02 ön yüz', 'Bereket Fide envanter tohum paketi 02 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 02 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0005', 'bf-inv-seed-img-0005', 'tr', 'Envanter tohum paketi 03 arka yüz', 'Bereket Fide envanter tohum paketi 03 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 03 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0006', 'bf-inv-seed-img-0006', 'tr', 'Envanter tohum paketi 03 ön yüz', 'Bereket Fide envanter tohum paketi 03 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 03 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0007', 'bf-inv-seed-img-0007', 'tr', 'Envanter tohum paketi 04 arka yüz', 'Bereket Fide envanter tohum paketi 04 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 04 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0008', 'bf-inv-seed-img-0008', 'tr', 'Envanter tohum paketi 04 ön yüz', 'Bereket Fide envanter tohum paketi 04 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 04 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0009', 'bf-inv-seed-img-0009', 'tr', 'Envanter tohum paketi 05 arka yüz', 'Bereket Fide envanter tohum paketi 05 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 05 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0010', 'bf-inv-seed-img-0010', 'tr', 'Envanter tohum paketi 05 ön yüz', 'Bereket Fide envanter tohum paketi 05 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 05 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0011', 'bf-inv-seed-img-0011', 'tr', 'Envanter tohum paketi 06 arka yüz', 'Bereket Fide envanter tohum paketi 06 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 06 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0012', 'bf-inv-seed-img-0012', 'tr', 'Envanter tohum paketi 06 ön yüz', 'Bereket Fide envanter tohum paketi 06 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 06 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0013', 'bf-inv-seed-img-0013', 'tr', 'Envanter tohum paketi 07 arka yüz', 'Bereket Fide envanter tohum paketi 07 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 07 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0014', 'bf-inv-seed-img-0014', 'tr', 'Envanter tohum paketi 07 ön yüz', 'Bereket Fide envanter tohum paketi 07 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 07 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0015', 'bf-inv-seed-img-0015', 'tr', 'Envanter tohum paketi 08 arka yüz', 'Bereket Fide envanter tohum paketi 08 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 08 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0016', 'bf-inv-seed-img-0016', 'tr', 'Envanter tohum paketi 08 ön yüz', 'Bereket Fide envanter tohum paketi 08 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 08 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0017', 'bf-inv-seed-img-0017', 'tr', 'Envanter tohum paketi 09 arka yüz', 'Bereket Fide envanter tohum paketi 09 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 09 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0018', 'bf-inv-seed-img-0018', 'tr', 'Envanter tohum paketi 09 ön yüz', 'Bereket Fide envanter tohum paketi 09 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 09 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0019', 'bf-inv-seed-img-0019', 'tr', 'Envanter tohum paketi 10 arka yüz', 'Bereket Fide envanter tohum paketi 10 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 10 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0020', 'bf-inv-seed-img-0020', 'tr', 'Envanter tohum paketi 10 ön yüz', 'Bereket Fide envanter tohum paketi 10 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 10 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0021', 'bf-inv-seed-img-0021', 'tr', 'Envanter tohum paketi 11 arka yüz', 'Bereket Fide envanter tohum paketi 11 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 11 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0022', 'bf-inv-seed-img-0022', 'tr', 'Envanter tohum paketi 11 ön yüz', 'Bereket Fide envanter tohum paketi 11 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 11 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0023', 'bf-inv-seed-img-0023', 'tr', 'Envanter tohum paketi 12 arka yüz', 'Bereket Fide envanter tohum paketi 12 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 12 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0024', 'bf-inv-seed-img-0024', 'tr', 'Envanter tohum paketi 12 ön yüz', 'Bereket Fide envanter tohum paketi 12 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 12 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0025', 'bf-inv-seed-img-0025', 'tr', 'Envanter tohum paketi 13 arka yüz', 'Bereket Fide envanter tohum paketi 13 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 13 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0026', 'bf-inv-seed-img-0026', 'tr', 'Envanter tohum paketi 13 ön yüz', 'Bereket Fide envanter tohum paketi 13 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 13 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0027', 'bf-inv-seed-img-0027', 'tr', 'Envanter tohum paketi 14 arka yüz', 'Bereket Fide envanter tohum paketi 14 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 14 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0028', 'bf-inv-seed-img-0028', 'tr', 'Envanter tohum paketi 14 ön yüz', 'Bereket Fide envanter tohum paketi 14 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 14 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0029', 'bf-inv-seed-img-0029', 'tr', 'Envanter tohum paketi 15 arka yüz', 'Bereket Fide envanter tohum paketi 15 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 15 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0030', 'bf-inv-seed-img-0030', 'tr', 'Envanter tohum paketi 15 ön yüz', 'Bereket Fide envanter tohum paketi 15 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 15 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0031', 'bf-inv-seed-img-0031', 'tr', 'Envanter tohum paketi 16 arka yüz', 'Bereket Fide envanter tohum paketi 16 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 16 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0032', 'bf-inv-seed-img-0032', 'tr', 'Envanter tohum paketi 16 ön yüz', 'Bereket Fide envanter tohum paketi 16 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 16 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0033', 'bf-inv-seed-img-0033', 'tr', 'Envanter tohum paketi 17 arka yüz', 'Bereket Fide envanter tohum paketi 17 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 17 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0034', 'bf-inv-seed-img-0034', 'tr', 'Envanter tohum paketi 17 ön yüz', 'Bereket Fide envanter tohum paketi 17 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 17 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0035', 'bf-inv-seed-img-0035', 'tr', 'Envanter tohum paketi 18 arka yüz', 'Bereket Fide envanter tohum paketi 18 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 18 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0036', 'bf-inv-seed-img-0036', 'tr', 'Envanter tohum paketi 18 ön yüz', 'Bereket Fide envanter tohum paketi 18 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 18 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0037', 'bf-inv-seed-img-0037', 'tr', 'Envanter tohum paketi 19 arka yüz', 'Bereket Fide envanter tohum paketi 19 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 19 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0038', 'bf-inv-seed-img-0038', 'tr', 'Envanter tohum paketi 19 ön yüz', 'Bereket Fide envanter tohum paketi 19 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 19 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0039', 'bf-inv-seed-img-0039', 'tr', 'Envanter tohum paketi 20 arka yüz', 'Bereket Fide envanter tohum paketi 20 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 20 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0040', 'bf-inv-seed-img-0040', 'tr', 'Envanter tohum paketi 20 ön yüz', 'Bereket Fide envanter tohum paketi 20 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 20 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0041', 'bf-inv-seed-img-0041', 'tr', 'Envanter tohum paketi 21 arka yüz', 'Bereket Fide envanter tohum paketi 21 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 21 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0042', 'bf-inv-seed-img-0042', 'tr', 'Envanter tohum paketi 21 ön yüz', 'Bereket Fide envanter tohum paketi 21 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 21 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0043', 'bf-inv-seed-img-0043', 'tr', 'Envanter tohum paketi 22 arka yüz', 'Bereket Fide envanter tohum paketi 22 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 22 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0044', 'bf-inv-seed-img-0044', 'tr', 'Envanter tohum paketi 22 ön yüz', 'Bereket Fide envanter tohum paketi 22 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 22 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0045', 'bf-inv-seed-img-0045', 'tr', 'Envanter tohum paketi 23 arka yüz', 'Bereket Fide envanter tohum paketi 23 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 23 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0046', 'bf-inv-seed-img-0046', 'tr', 'Envanter tohum paketi 23 ön yüz', 'Bereket Fide envanter tohum paketi 23 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 23 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0047', 'bf-inv-seed-img-0047', 'tr', 'Envanter tohum paketi 24 arka yüz', 'Bereket Fide envanter tohum paketi 24 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 24 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0048', 'bf-inv-seed-img-0048', 'tr', 'Envanter tohum paketi 24 ön yüz', 'Bereket Fide envanter tohum paketi 24 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 24 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0049', 'bf-inv-seed-img-0049', 'tr', 'Envanter tohum paketi 25 arka yüz', 'Bereket Fide envanter tohum paketi 25 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 25 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0050', 'bf-inv-seed-img-0050', 'tr', 'Envanter tohum paketi 25 ön yüz', 'Bereket Fide envanter tohum paketi 25 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 25 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0051', 'bf-inv-seed-img-0051', 'tr', 'Envanter tohum paketi 26 arka yüz', 'Bereket Fide envanter tohum paketi 26 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 26 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0052', 'bf-inv-seed-img-0052', 'tr', 'Envanter tohum paketi 26 ön yüz', 'Bereket Fide envanter tohum paketi 26 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 26 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0053', 'bf-inv-seed-img-0053', 'tr', 'Envanter tohum paketi 27 arka yüz', 'Bereket Fide envanter tohum paketi 27 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 27 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0054', 'bf-inv-seed-img-0054', 'tr', 'Envanter tohum paketi 27 ön yüz', 'Bereket Fide envanter tohum paketi 27 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 27 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0055', 'bf-inv-seed-img-0055', 'tr', 'Envanter tohum paketi 28 arka yüz', 'Bereket Fide envanter tohum paketi 28 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 28 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0056', 'bf-inv-seed-img-0056', 'tr', 'Envanter tohum paketi 28 ön yüz', 'Bereket Fide envanter tohum paketi 28 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 28 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0057', 'bf-inv-seed-img-0057', 'tr', 'Envanter tohum paketi 29 arka yüz', 'Bereket Fide envanter tohum paketi 29 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 29 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0058', 'bf-inv-seed-img-0058', 'tr', 'Envanter tohum paketi 29 ön yüz', 'Bereket Fide envanter tohum paketi 29 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 29 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0059', 'bf-inv-seed-img-0059', 'tr', 'Envanter tohum paketi 30 arka yüz', 'Bereket Fide envanter tohum paketi 30 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 30 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0060', 'bf-inv-seed-img-0060', 'tr', 'Envanter tohum paketi 30 ön yüz', 'Bereket Fide envanter tohum paketi 30 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 30 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0061', 'bf-inv-seed-img-0061', 'tr', 'Envanter tohum paketi 31 arka yüz', 'Bereket Fide envanter tohum paketi 31 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 31 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0062', 'bf-inv-seed-img-0062', 'tr', 'Envanter tohum paketi 31 ön yüz', 'Bereket Fide envanter tohum paketi 31 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 31 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0063', 'bf-inv-seed-img-0063', 'tr', 'Envanter tohum paketi 32 arka yüz', 'Bereket Fide envanter tohum paketi 32 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 32 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0064', 'bf-inv-seed-img-0064', 'tr', 'Envanter tohum paketi 32 ön yüz', 'Bereket Fide envanter tohum paketi 32 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 32 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0065', 'bf-inv-seed-img-0065', 'tr', 'Envanter tohum paketi 33 arka yüz', 'Bereket Fide envanter tohum paketi 33 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 33 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0066', 'bf-inv-seed-img-0066', 'tr', 'Envanter tohum paketi 33 ön yüz', 'Bereket Fide envanter tohum paketi 33 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 33 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0067', 'bf-inv-seed-img-0067', 'tr', 'Envanter tohum paketi 34 arka yüz', 'Bereket Fide envanter tohum paketi 34 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 34 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0068', 'bf-inv-seed-img-0068', 'tr', 'Envanter tohum paketi 34 ön yüz', 'Bereket Fide envanter tohum paketi 34 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 34 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0069', 'bf-inv-seed-img-0069', 'tr', 'Envanter tohum paketi 35 arka yüz', 'Bereket Fide envanter tohum paketi 35 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 35 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0070', 'bf-inv-seed-img-0070', 'tr', 'Envanter tohum paketi 35 ön yüz', 'Bereket Fide envanter tohum paketi 35 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 35 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0071', 'bf-inv-seed-img-0071', 'tr', 'Envanter tohum paketi 36 arka yüz', 'Bereket Fide envanter tohum paketi 36 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 36 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0072', 'bf-inv-seed-img-0072', 'tr', 'Envanter tohum paketi 36 ön yüz', 'Bereket Fide envanter tohum paketi 36 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 36 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0073', 'bf-inv-seed-img-0073', 'tr', 'Envanter tohum paketi 37 arka yüz', 'Bereket Fide envanter tohum paketi 37 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 37 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0074', 'bf-inv-seed-img-0074', 'tr', 'Envanter tohum paketi 37 ön yüz', 'Bereket Fide envanter tohum paketi 37 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 37 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0075', 'bf-inv-seed-img-0075', 'tr', 'Envanter tohum paketi 38 arka yüz', 'Bereket Fide envanter tohum paketi 38 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 38 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0076', 'bf-inv-seed-img-0076', 'tr', 'Envanter tohum paketi 38 ön yüz', 'Bereket Fide envanter tohum paketi 38 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 38 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0077', 'bf-inv-seed-img-0077', 'tr', 'Envanter tohum paketi 39 arka yüz', 'Bereket Fide envanter tohum paketi 39 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 39 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0078', 'bf-inv-seed-img-0078', 'tr', 'Envanter tohum paketi 39 ön yüz', 'Bereket Fide envanter tohum paketi 39 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 39 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0079', 'bf-inv-seed-img-0079', 'tr', 'Envanter tohum paketi 40 arka yüz', 'Bereket Fide envanter tohum paketi 40 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 40 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0080', 'bf-inv-seed-img-0080', 'tr', 'Envanter tohum paketi 40 ön yüz', 'Bereket Fide envanter tohum paketi 40 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 40 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0081', 'bf-inv-seed-img-0081', 'tr', 'Envanter tohum paketi 41 arka yüz', 'Bereket Fide envanter tohum paketi 41 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 41 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0082', 'bf-inv-seed-img-0082', 'tr', 'Envanter tohum paketi 41 ön yüz', 'Bereket Fide envanter tohum paketi 41 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 41 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0083', 'bf-inv-seed-img-0083', 'tr', 'Envanter tohum paketi 42 arka yüz', 'Bereket Fide envanter tohum paketi 42 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 42 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0084', 'bf-inv-seed-img-0084', 'tr', 'Envanter tohum paketi 42 ön yüz', 'Bereket Fide envanter tohum paketi 42 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 42 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0085', 'bf-inv-seed-img-0085', 'tr', 'Envanter tohum paketi 43 arka yüz', 'Bereket Fide envanter tohum paketi 43 arka yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 43 arka yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW()),
  ('bf-inv-seed-tr-0086', 'bf-inv-seed-img-0086', 'tr', 'Envanter tohum paketi 43 ön yüz', 'Bereket Fide envanter tohum paketi 43 ön yüz görseli', 'Envanter eşleştirme için düzenlenmiş tohum paketi 43 ön yüz fotoğrafı.', 'Canlı envanter ürünleriyle eşleştirmek için hazırlanan düzenlenmiş paket görseli.', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  alt = VALUES(alt),
  caption = VALUES(caption),
  description = VALUES(description),
  updated_at = NOW();

COMMIT;
SET FOREIGN_KEY_CHECKS = 1;
