-- =============================================================
-- 046_seo_config.sql – Bereket Fide SEO ayarları
-- Key'ler frontend route'larıyla birebir eşleşir
-- =============================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- Global SEO (seo + site_seo + prefixed)
INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`, `created_at`, `updated_at`) VALUES
(UUID(), 'seo', 'tr', '{"site_name":"Bereket Fide","title_default":"Bereket Fide | Kaliteli Fide Üretimi","title_template":"%s – Bereket Fide","description":"Modern seralarda aşılı ve standart domates, biber, salatalık fidesi üretimi.","open_graph":{"type":"website","images":["/logo/bereket-logo-light.png"]},"twitter":{"card":"summary_large_image","site":"@bereketfide"},"robots":{"index":true,"follow":true}}', NOW(3), NOW(3)),
(UUID(), 'seo', 'en', '{"site_name":"Bereket Fide","title_default":"Bereket Fide | Quality Seedling Production","title_template":"%s – Bereket Fide","description":"Modern greenhouse grafted and standard seedling production.","open_graph":{"type":"website","images":["/logo/bereket-logo-light.png"]},"twitter":{"card":"summary_large_image","site":"@bereketfide"},"robots":{"index":true,"follow":true}}', NOW(3), NOW(3)),
(UUID(), 'seo', '*', '{"site_name":"Bereket Fide","title_default":"Bereket Fide","title_template":"%s – Bereket Fide","description":"Quality seedling production.","open_graph":{"type":"website"},"twitter":{"card":"summary_large_image","site":"@bereketfide"},"robots":{"index":true,"follow":true}}', NOW(3), NOW(3)),
(UUID(), 'bereketfide__seo', 'tr', '{"site_title":"Bereket Fide | Kaliteli ve Yüksek Verimli Fide Üretimi","site_description":"Antalya Aksu''da 2006''dan beri modern seralarda aşılı ve normal domates, biber, salatalık fideleri üretimi.","keywords":"bereket fide, antalya fide, aşılı fide, domates fidesi, biber fidesi, sebze fidesi","og_image":"","og_type":"website"}', NOW(3), NOW(3)),
(UUID(), 'bereketfide__seo', 'en', '{"site_title":"Bereket Fide | High Quality and High Yield Seedling Production","site_description":"Production of grafted and standard seedlings in modern greenhouses in Antalya since 2006.","keywords":"bereket fide, grafted seedling, tomato seedling, vegetable seedling","og_image":"","og_type":"website"}', NOW(3), NOW(3)),

-- Per-page SEO — key'ler frontend route ile birebir eşleşir
(UUID(), 'seo_pages', 'tr', '{"home":{"title":"Bereket Fide | Kaliteli ve Yüksek Verimli Fide Üretimi","description":"Antalya merkezli modern seralarda aşılı ve standart domates, biber, salatalık fidesi üretimi.","og_image":"","no_index":false},"urunler":{"title":"Ürünlerimiz | Bereket Fide","description":"Aşılı ve standart domates, biber, salatalık, karpuz, kavun fideleri. Kaliteli fide çeşitlerimizi keşfedin.","og_image":"","no_index":false},"hizmetler":{"title":"Hizmetlerimiz | Bereket Fide","description":"Aşılı fide üretimi, teknik destek, lojistik ve fide bakım danışmanlığı hizmetlerimiz.","og_image":"","no_index":false},"galeri":{"title":"Galeri | Bereket Fide","description":"Seralarımızdan ve üretim süreçlerimizden görüntüler.","og_image":"","no_index":false},"haberler":{"title":"Haberler | Bereket Fide","description":"Bereket Fide güncel haberler, duyurular ve sektörel gelişmeler.","og_image":"","no_index":false},"blog":{"title":"Bilgi Bankası | Bereket Fide","description":"Fide yetiştiriciliği, teknik ipuçları, tarımsal bilgilendirmeler ve uzman tavsiyeleri.","og_image":"","no_index":false},"hakkimizda":{"title":"Hakkımızda | Bereket Fide","description":"2006''dan beri Antalya Aksu''da modern seralarda kaliteli fide üretimi yapan Bereket Fide''nin hikayesi.","og_image":"","no_index":false},"iletisim":{"title":"İletişim | Bereket Fide","description":"Bereket Fide ile iletişime geçin. Adres, telefon, e-posta ve harita bilgileri.","og_image":"","no_index":false},"teklif":{"title":"Teklif Al | Bereket Fide","description":"Fide siparişi için online teklif formu. Hızlı ve kolay fide siparişi verin.","og_image":"","no_index":false},"kataloglar":{"title":"Kataloglar | Bereket Fide","description":"Sebze, meyve ve aşılı fide kataloglarımızı indirin.","og_image":"","no_index":false},"legal_privacy":{"title":"Gizlilik Politikası | Bereket Fide","description":"Bereket Fide gizlilik politikası ve kişisel verilerin korunması hakkında bilgilendirme.","og_image":"","no_index":false},"legal_terms":{"title":"Kullanım Koşulları | Bereket Fide","description":"Bereket Fide web sitesi kullanım koşulları ve yasal bilgilendirme.","og_image":"","no_index":false}}', NOW(3), NOW(3)),
(UUID(), 'seo_pages', 'en', '{"home":{"title":"Bereket Fide | Quality Seedling Production","description":"Modern greenhouse seedling production in Antalya since 2006.","og_image":"","no_index":false},"urunler":{"title":"Products | Bereket Fide","description":"Grafted and standard tomato, pepper, cucumber, watermelon, melon seedlings.","og_image":"","no_index":false},"hizmetler":{"title":"Services | Bereket Fide","description":"Seedling production, technical support and logistics services.","og_image":"","no_index":false},"galeri":{"title":"Gallery | Bereket Fide","description":"Images from our greenhouses and production processes.","og_image":"","no_index":false},"haberler":{"title":"News | Bereket Fide","description":"Latest news, announcements and industry developments.","og_image":"","no_index":false},"blog":{"title":"Knowledge Base | Bereket Fide","description":"Seedling cultivation, technical tips and expert advice.","og_image":"","no_index":false},"hakkimizda":{"title":"About Us | Bereket Fide","description":"The story of Bereket Fide, producing quality seedlings since 2006.","og_image":"","no_index":false},"iletisim":{"title":"Contact | Bereket Fide","description":"Contact Bereket Fide. Address, phone, email and map.","og_image":"","no_index":false},"teklif":{"title":"Get a Quote | Bereket Fide","description":"Online quote form for seedling orders.","og_image":"","no_index":false},"kataloglar":{"title":"Catalogs | Bereket Fide","description":"Download our vegetable, fruit and grafted seedling catalogs.","og_image":"","no_index":false},"legal_privacy":{"title":"Privacy Policy | Bereket Fide","description":"Bereket Fide privacy policy.","og_image":"","no_index":false},"legal_terms":{"title":"Terms of Use | Bereket Fide","description":"Bereket Fide website terms of use.","og_image":"","no_index":false}}', NOW(3), NOW(3)),
(UUID(), 'seo_pages', '*', '{"home":{"title":"Bereket Fide","description":"Quality seedling production.","og_image":"","no_index":false}}', NOW(3), NOW(3)),
-- Prefixed versions
(UUID(), 'bereketfide__seo_pages', 'tr', '{"home":{"title":"Bereket Fide | Kaliteli ve Yüksek Verimli Fide Üretimi","description":"Antalya merkezli modern seralarda aşılı ve standart domates, biber, salatalık fidesi üretimi.","og_image":"","no_index":false},"urunler":{"title":"Ürünlerimiz | Bereket Fide","description":"Aşılı ve standart domates, biber, salatalık, karpuz, kavun fideleri.","og_image":"","no_index":false},"hizmetler":{"title":"Hizmetlerimiz | Bereket Fide","description":"Aşılı fide üretimi, teknik destek ve lojistik hizmetlerimiz.","og_image":"","no_index":false},"galeri":{"title":"Galeri | Bereket Fide","description":"Seralarımızdan görüntüler.","og_image":"","no_index":false},"haberler":{"title":"Haberler | Bereket Fide","description":"Güncel haberler ve duyurular.","og_image":"","no_index":false},"blog":{"title":"Bilgi Bankası | Bereket Fide","description":"Fide yetiştiriciliği, teknik ipuçları ve tarımsal bilgilendirmeler.","og_image":"","no_index":false},"hakkimizda":{"title":"Hakkımızda | Bereket Fide","description":"2006''dan beri kaliteli fide üretimi.","og_image":"","no_index":false},"iletisim":{"title":"İletişim | Bereket Fide","description":"Bereket Fide ile iletişime geçin.","og_image":"","no_index":false},"teklif":{"title":"Teklif Al | Bereket Fide","description":"Fide siparişi için teklif formu.","og_image":"","no_index":false},"kataloglar":{"title":"Kataloglar | Bereket Fide","description":"Fide kataloglarımızı indirin.","og_image":"","no_index":false},"legal_privacy":{"title":"Gizlilik Politikası | Bereket Fide","description":"Gizlilik politikamız.","og_image":"","no_index":false},"legal_terms":{"title":"Kullanım Koşulları | Bereket Fide","description":"Kullanım koşullarımız.","og_image":"","no_index":false}}', NOW(3), NOW(3)),
(UUID(), 'bereketfide__seo_pages', 'en', '{"home":{"title":"Bereket Fide | Quality Seedling Production","description":"Modern greenhouse seedling production since 2006.","og_image":"","no_index":false},"urunler":{"title":"Products | Bereket Fide","description":"Grafted and standard vegetable seedlings.","og_image":"","no_index":false},"hizmetler":{"title":"Services | Bereket Fide","description":"Seedling production and technical support.","og_image":"","no_index":false},"galeri":{"title":"Gallery | Bereket Fide","description":"Images from our greenhouses.","og_image":"","no_index":false},"haberler":{"title":"News | Bereket Fide","description":"Latest news and announcements.","og_image":"","no_index":false},"blog":{"title":"Knowledge Base | Bereket Fide","description":"Seedling tips and expert advice.","og_image":"","no_index":false},"hakkimizda":{"title":"About Us | Bereket Fide","description":"Quality seedling production since 2006.","og_image":"","no_index":false},"iletisim":{"title":"Contact | Bereket Fide","description":"Contact Bereket Fide.","og_image":"","no_index":false},"teklif":{"title":"Get a Quote | Bereket Fide","description":"Online seedling order form.","og_image":"","no_index":false},"kataloglar":{"title":"Catalogs | Bereket Fide","description":"Download seedling catalogs.","og_image":"","no_index":false},"legal_privacy":{"title":"Privacy Policy | Bereket Fide","description":"Our privacy policy.","og_image":"","no_index":false},"legal_terms":{"title":"Terms of Use | Bereket Fide","description":"Website terms of use.","og_image":"","no_index":false}}', NOW(3), NOW(3))
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = VALUES(`updated_at`);
