-- =============================================================
-- 046_seo_config.sql – Bereket Fide SEO ayarları
-- =============================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- Global SEO (seo + site_seo + prefixed)
INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`, `created_at`, `updated_at`) VALUES
(UUID(), 'seo', 'tr', '{"site_name":"Bereket Fide","title_default":"Bereket Fide | Kaliteli Fide Üretimi","title_template":"%s – Bereket Fide","description":"Modern seralarda aşılı ve standart domates, biber, salatalık fidesi üretimi.","open_graph":{"type":"website","images":["/logo/bereket-logo-light.png"]},"twitter":{"card":"summary_large_image","site":"@bereketfide"},"robots":{"index":true,"follow":true}}', NOW(3), NOW(3)),
(UUID(), 'seo', 'en', '{"site_name":"Bereket Fide","title_default":"Bereket Fide | Quality Seedling Production","title_template":"%s – Bereket Fide","description":"Modern greenhouse grafted and standard seedling production.","open_graph":{"type":"website","images":["/logo/bereket-logo-light.png"]},"twitter":{"card":"summary_large_image","site":"@bereketfide"},"robots":{"index":true,"follow":true}}', NOW(3), NOW(3)),
(UUID(), 'seo', 'de', '{"site_name":"Bereket Fide","title_default":"Bereket Fide | Qualitäts-Setzlingsproduktion","title_template":"%s – Bereket Fide","description":"Moderne Gewächshäuser für veredelte und Standard-Setzlinge.","open_graph":{"type":"website","images":["/logo/bereket-logo-light.png"]},"twitter":{"card":"summary_large_image","site":"@bereketfide"},"robots":{"index":true,"follow":true}}', NOW(3), NOW(3)),
(UUID(), 'seo', '*', '{"site_name":"Bereket Fide","title_default":"Bereket Fide","title_template":"%s – Bereket Fide","description":"Quality seedling production.","open_graph":{"type":"website"},"twitter":{"card":"summary_large_image","site":"@bereketfide"},"robots":{"index":true,"follow":true}}', NOW(3), NOW(3)),
(UUID(), 'bereketfide__seo', 'tr', '{"site_title":"Bereket Fide | Kaliteli ve Yüksek Verimli Fide Üretimi","site_description":"Antalya Aksu''da 2006''dan beri modern seralarda aşılı ve normal domates, biber, salatalık fideleri üretimi.","keywords":"bereket fide, antalya fide, aşılı fide, domates fidesi, biber fidesi, sebze fidesi","og_image":"","og_type":"website"}', NOW(3), NOW(3)),
(UUID(), 'bereketfide__seo', 'en', '{"site_title":"Bereket Fide | High Quality and High Yield Seedling Production","site_description":"Production of grafted and standard seedlings in modern greenhouses in Antalya since 2006.","keywords":"bereket fide, grafted seedling, tomato seedling, vegetable seedling","og_image":"","og_type":"website"}', NOW(3), NOW(3)),
-- Per-page SEO
(UUID(), 'seo_pages', 'tr', '{"home":{"title":"Bereket Fide | Kaliteli ve Yüksek Verimli Fide Üretimi","description":"Antalya merkezli modern seralarda aşılı ve standart domates, biber, salatalık fidesi üretimi.","no_index":false},"products":{"title":"Ürünlerimiz | Bereket Fide","description":"Aşılı ve standart sebze fideleri.","no_index":false},"services":{"title":"Hizmetlerimiz | Bereket Fide","description":"Aşılı fide üretimi, teknik destek, lojistik.","no_index":false},"about":{"title":"Hakkımızda | Bereket Fide","description":"2006''dan beri kaliteli fide üretimi.","no_index":false},"contact":{"title":"İletişim | Bereket Fide","description":"Bereket Fide ile iletişime geçin.","no_index":false},"gallery":{"title":"Galeri | Bereket Fide","description":"Seralarımızdan görüntüler.","no_index":false},"blog":{"title":"Haberler | Bereket Fide","description":"Tarım haberleri.","no_index":false},"offer":{"title":"Teklif Al | Bereket Fide","description":"Fide siparişi için teklif formu.","no_index":false}}', NOW(3), NOW(3)),
(UUID(), 'seo_pages', 'en', '{"home":{"title":"Bereket Fide | Quality Seedling Production","description":"Modern greenhouse seedling production since 2006.","no_index":false},"products":{"title":"Products | Bereket Fide","description":"Grafted and standard vegetable seedlings.","no_index":false},"services":{"title":"Services | Bereket Fide","description":"Seedling production and technical support.","no_index":false},"about":{"title":"About Us | Bereket Fide","description":"Quality seedling production since 2006.","no_index":false},"contact":{"title":"Contact | Bereket Fide","description":"Contact Bereket Fide.","no_index":false}}', NOW(3), NOW(3)),
(UUID(), 'seo_pages', '*', '{"home":{"title":"Bereket Fide","description":"Quality seedling production.","no_index":false}}', NOW(3), NOW(3)),
(UUID(), 'bereketfide__seo_pages', 'tr', '{"home":{"title":"Bereket Fide | Kaliteli ve Yüksek Verimli Fide Üretimi","description":"Antalya merkezli modern seralarda aşılı ve standart domates, biber, salatalık fidesi üretimi.","no_index":false},"products":{"title":"Ürünlerimiz | Bereket Fide","description":"Aşılı ve standart sebze fideleri.","no_index":false},"services":{"title":"Hizmetlerimiz | Bereket Fide","description":"Aşılı fide üretimi, teknik destek.","no_index":false},"about":{"title":"Hakkımızda | Bereket Fide","description":"2006''dan beri kaliteli fide üretimi.","no_index":false},"contact":{"title":"İletişim | Bereket Fide","description":"Bereket Fide ile iletişime geçin.","no_index":false},"gallery":{"title":"Galeri | Bereket Fide","description":"Seralarımızdan görüntüler.","no_index":false},"blog":{"title":"Haberler | Bereket Fide","description":"Tarım haberleri.","no_index":false},"offer":{"title":"Teklif Al | Bereket Fide","description":"Fide siparişi için teklif formu.","no_index":false}}', NOW(3), NOW(3))
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = VALUES(`updated_at`);
