-- =============================================================
-- FILE: 131_bereketfide_storage_assets.seed.sql
-- Bereket Fide — Local Storage Assets (uploads/)
-- =============================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET FOREIGN_KEY_CHECKS = 0;

START TRANSACTION;

-- =========================
-- PRODUCT IMAGES
-- =========================
INSERT INTO `storage_assets`
(`id`, `user_id`, `name`, `bucket`, `path`, `folder`, `mime`, `size`, `width`, `height`, `url`, `hash`, `provider`, `provider_public_id`, `provider_resource_type`, `provider_format`, `provider_version`, `etag`, `metadata`, `created_at`, `updated_at`)
VALUES
  ('bf-prd-img-0004', NULL, '23.27.59 (1).jpeg', 'products', 'products/23.27.59 (1).jpeg', 'products', 'image/jpeg', 385060, 800, 800, '/uploads/products/23.27.59 (1).jpeg', NULL, 'local', 'products/23.27.59 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0005', NULL, '23.27.59.jpeg', 'products', 'products/23.27.59.jpeg', 'products', 'image/jpeg', 397190, 800, 800, '/uploads/products/23.27.59.jpeg', NULL, 'local', 'products/23.27.59.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0006', NULL, '23.28.00.jpeg', 'products', 'products/23.28.00.jpeg', 'products', 'image/jpeg', 277119, 800, 800, '/uploads/products/23.28.00.jpeg', NULL, 'local', 'products/23.28.00.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0007', NULL, '23.28.01.jpeg', 'products', 'products/23.28.01.jpeg', 'products', 'image/jpeg', 406875, 800, 800, '/uploads/products/23.28.01.jpeg', NULL, 'local', 'products/23.28.01.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0008', NULL, '23.28.04.jpeg', 'products', 'products/23.28.04.jpeg', 'products', 'image/jpeg', 414644, 800, 800, '/uploads/products/23.28.04.jpeg', NULL, 'local', 'products/23.28.04.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0009', NULL, '23.28.05.jpeg', 'products', 'products/23.28.05.jpeg', 'products', 'image/jpeg', 420753, 800, 800, '/uploads/products/23.28.05.jpeg', NULL, 'local', 'products/23.28.05.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0010', NULL, '23.28.06 (1).jpeg', 'products', 'products/23.28.06 (1).jpeg', 'products', 'image/jpeg', 333178, 800, 800, '/uploads/products/23.28.06 (1).jpeg', NULL, 'local', 'products/23.28.06 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0011', NULL, '23.28.06.jpeg', 'products', 'products/23.28.06.jpeg', 'products', 'image/jpeg', 224503, 800, 800, '/uploads/products/23.28.06.jpeg', NULL, 'local', 'products/23.28.06.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0012', NULL, '23.28.07 (1).jpeg', 'products', 'products/23.28.07 (1).jpeg', 'products', 'image/jpeg', 243201, 800, 800, '/uploads/products/23.28.07 (1).jpeg', NULL, 'local', 'products/23.28.07 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0013', NULL, '23.28.07 (2).jpeg', 'products', 'products/23.28.07 (2).jpeg', 'products', 'image/jpeg', 231762, 800, 800, '/uploads/products/23.28.07 (2).jpeg', NULL, 'local', 'products/23.28.07 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0014', NULL, '23.28.07 (3).jpeg', 'products', 'products/23.28.07 (3).jpeg', 'products', 'image/jpeg', 252813, 800, 800, '/uploads/products/23.28.07 (3).jpeg', NULL, 'local', 'products/23.28.07 (3).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0015', NULL, '23.28.07.jpeg', 'products', 'products/23.28.07.jpeg', 'products', 'image/jpeg', 286311, 800, 800, '/uploads/products/23.28.07.jpeg', NULL, 'local', 'products/23.28.07.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0016', NULL, '23.28.08 (1).jpeg', 'products', 'products/23.28.08 (1).jpeg', 'products', 'image/jpeg', 253872, 800, 800, '/uploads/products/23.28.08 (1).jpeg', NULL, 'local', 'products/23.28.08 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0017', NULL, '23.28.08 (2).jpeg', 'products', 'products/23.28.08 (2).jpeg', 'products', 'image/jpeg', 249574, 800, 800, '/uploads/products/23.28.08 (2).jpeg', NULL, 'local', 'products/23.28.08 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0018', NULL, '23.28.08 (3).jpeg', 'products', 'products/23.28.08 (3).jpeg', 'products', 'image/jpeg', 310105, 800, 800, '/uploads/products/23.28.08 (3).jpeg', NULL, 'local', 'products/23.28.08 (3).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0019', NULL, '23.28.08.jpeg', 'products', 'products/23.28.08.jpeg', 'products', 'image/jpeg', 275008, 800, 800, '/uploads/products/23.28.08.jpeg', NULL, 'local', 'products/23.28.08.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0020', NULL, '23.28.09 (1).jpeg', 'products', 'products/23.28.09 (1).jpeg', 'products', 'image/jpeg', 272781, 800, 800, '/uploads/products/23.28.09 (1).jpeg', NULL, 'local', 'products/23.28.09 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0021', NULL, '23.28.09 (2).jpeg', 'products', 'products/23.28.09 (2).jpeg', 'products', 'image/jpeg', 251004, 800, 800, '/uploads/products/23.28.09 (2).jpeg', NULL, 'local', 'products/23.28.09 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0022', NULL, '23.28.09.jpeg', 'products', 'products/23.28.09.jpeg', 'products', 'image/jpeg', 273132, 800, 800, '/uploads/products/23.28.09.jpeg', NULL, 'local', 'products/23.28.09.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0023', NULL, '23.28.13 (1).jpeg', 'products', 'products/23.28.13 (1).jpeg', 'products', 'image/jpeg', 395019, 800, 800, '/uploads/products/23.28.13 (1).jpeg', NULL, 'local', 'products/23.28.13 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0024', NULL, '23.28.13.jpeg', 'products', 'products/23.28.13.jpeg', 'products', 'image/jpeg', 402847, 800, 800, '/uploads/products/23.28.13.jpeg', NULL, 'local', 'products/23.28.13.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0025', NULL, '23.28.14 (1).jpeg', 'products', 'products/23.28.14 (1).jpeg', 'products', 'image/jpeg', 348929, 800, 800, '/uploads/products/23.28.14 (1).jpeg', NULL, 'local', 'products/23.28.14 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0026', NULL, '23.28.14.jpeg', 'products', 'products/23.28.14.jpeg', 'products', 'image/jpeg', 413685, 800, 800, '/uploads/products/23.28.14.jpeg', NULL, 'local', 'products/23.28.14.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0027', NULL, '23.28.15 (1).jpeg', 'products', 'products/23.28.15 (1).jpeg', 'products', 'image/jpeg', 283132, 800, 800, '/uploads/products/23.28.15 (1).jpeg', NULL, 'local', 'products/23.28.15 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0028', NULL, '23.28.15 (2).jpeg', 'products', 'products/23.28.15 (2).jpeg', 'products', 'image/jpeg', 303321, 800, 800, '/uploads/products/23.28.15 (2).jpeg', NULL, 'local', 'products/23.28.15 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0029', NULL, '23.28.15 (3).jpeg', 'products', 'products/23.28.15 (3).jpeg', 'products', 'image/jpeg', 196783, 800, 800, '/uploads/products/23.28.15 (3).jpeg', NULL, 'local', 'products/23.28.15 (3).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0030', NULL, '23.28.15 (4).jpeg', 'products', 'products/23.28.15 (4).jpeg', 'products', 'image/jpeg', 197365, 800, 800, '/uploads/products/23.28.15 (4).jpeg', NULL, 'local', 'products/23.28.15 (4).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0031', NULL, '23.28.15 (5).jpeg', 'products', 'products/23.28.15 (5).jpeg', 'products', 'image/jpeg', 193605, 800, 800, '/uploads/products/23.28.15 (5).jpeg', NULL, 'local', 'products/23.28.15 (5).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0032', NULL, '23.28.15 (6).jpeg', 'products', 'products/23.28.15 (6).jpeg', 'products', 'image/jpeg', 206262, 800, 800, '/uploads/products/23.28.15 (6).jpeg', NULL, 'local', 'products/23.28.15 (6).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0033', NULL, '23.28.15.jpeg', 'products', 'products/23.28.15.jpeg', 'products', 'image/jpeg', 242241, 800, 800, '/uploads/products/23.28.15.jpeg', NULL, 'local', 'products/23.28.15.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0034', NULL, '23.28.16 (1).jpeg', 'products', 'products/23.28.16 (1).jpeg', 'products', 'image/jpeg', 333342, 800, 800, '/uploads/products/23.28.16 (1).jpeg', NULL, 'local', 'products/23.28.16 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0035', NULL, '23.28.16 (2).jpeg', 'products', 'products/23.28.16 (2).jpeg', 'products', 'image/jpeg', 324035, 800, 800, '/uploads/products/23.28.16 (2).jpeg', NULL, 'local', 'products/23.28.16 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0036', NULL, '23.28.16.jpeg', 'products', 'products/23.28.16.jpeg', 'products', 'image/jpeg', 420992, 800, 800, '/uploads/products/23.28.16.jpeg', NULL, 'local', 'products/23.28.16.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0037', NULL, '23.28.17 (1).jpeg', 'products', 'products/23.28.17 (1).jpeg', 'products', 'image/jpeg', 412629, 800, 800, '/uploads/products/23.28.17 (1).jpeg', NULL, 'local', 'products/23.28.17 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0038', NULL, '23.28.17 (2).jpeg', 'products', 'products/23.28.17 (2).jpeg', 'products', 'image/jpeg', 320022, 800, 800, '/uploads/products/23.28.17 (2).jpeg', NULL, 'local', 'products/23.28.17 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0039', NULL, '23.28.17 (3).jpeg', 'products', 'products/23.28.17 (3).jpeg', 'products', 'image/jpeg', 409462, 800, 800, '/uploads/products/23.28.17 (3).jpeg', NULL, 'local', 'products/23.28.17 (3).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0040', NULL, '23.28.17.jpeg', 'products', 'products/23.28.17.jpeg', 'products', 'image/jpeg', 371916, 800, 800, '/uploads/products/23.28.17.jpeg', NULL, 'local', 'products/23.28.17.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0041', NULL, '23.28.20.jpeg', 'products', 'products/23.28.20.jpeg', 'products', 'image/jpeg', 410306, 800, 800, '/uploads/products/23.28.20.jpeg', NULL, 'local', 'products/23.28.20.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0042', NULL, '23.28.22 (1).jpeg', 'products', 'products/23.28.22 (1).jpeg', 'products', 'image/jpeg', 484027, 800, 800, '/uploads/products/23.28.22 (1).jpeg', NULL, 'local', 'products/23.28.22 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0043', NULL, '23.28.22 (2).jpeg', 'products', 'products/23.28.22 (2).jpeg', 'products', 'image/jpeg', 460909, 800, 800, '/uploads/products/23.28.22 (2).jpeg', NULL, 'local', 'products/23.28.22 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0044', NULL, '23.28.22.jpeg', 'products', 'products/23.28.22.jpeg', 'products', 'image/jpeg', 371084, 800, 800, '/uploads/products/23.28.22.jpeg', NULL, 'local', 'products/23.28.22.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0045', NULL, '23.28.23.jpeg', 'products', 'products/23.28.23.jpeg', 'products', 'image/jpeg', 573767, 800, 800, '/uploads/products/23.28.23.jpeg', NULL, 'local', 'products/23.28.23.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0046', NULL, '23.28.30 (1).jpeg', 'products', 'products/23.28.30 (1).jpeg', 'products', 'image/jpeg', 455935, 800, 800, '/uploads/products/23.28.30 (1).jpeg', NULL, 'local', 'products/23.28.30 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0047', NULL, '23.28.30 (2).jpeg', 'products', 'products/23.28.30 (2).jpeg', 'products', 'image/jpeg', 246719, 800, 800, '/uploads/products/23.28.30 (2).jpeg', NULL, 'local', 'products/23.28.30 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0048', NULL, '23.28.30.jpeg', 'products', 'products/23.28.30.jpeg', 'products', 'image/jpeg', 467987, 800, 800, '/uploads/products/23.28.30.jpeg', NULL, 'local', 'products/23.28.30.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0049', NULL, '23.28.31 (1).jpeg', 'products', 'products/23.28.31 (1).jpeg', 'products', 'image/jpeg', 342762, 800, 800, '/uploads/products/23.28.31 (1).jpeg', NULL, 'local', 'products/23.28.31 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0050', NULL, '23.28.31 (2).jpeg', 'products', 'products/23.28.31 (2).jpeg', 'products', 'image/jpeg', 176797, 800, 800, '/uploads/products/23.28.31 (2).jpeg', NULL, 'local', 'products/23.28.31 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0051', NULL, '23.28.31.jpeg', 'products', 'products/23.28.31.jpeg', 'products', 'image/jpeg', 214337, 800, 800, '/uploads/products/23.28.31.jpeg', NULL, 'local', 'products/23.28.31.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0052', NULL, '23.28.32 (1).jpeg', 'products', 'products/23.28.32 (1).jpeg', 'products', 'image/jpeg', 161300, 800, 800, '/uploads/products/23.28.32 (1).jpeg', NULL, 'local', 'products/23.28.32 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0053', NULL, '23.28.32 (2).jpeg', 'products', 'products/23.28.32 (2).jpeg', 'products', 'image/jpeg', 152459, 800, 800, '/uploads/products/23.28.32 (2).jpeg', NULL, 'local', 'products/23.28.32 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0054', NULL, '23.28.32.jpeg', 'products', 'products/23.28.32.jpeg', 'products', 'image/jpeg', 182623, 800, 800, '/uploads/products/23.28.32.jpeg', NULL, 'local', 'products/23.28.32.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0055', NULL, '23.28.33 (1).jpeg', 'products', 'products/23.28.33 (1).jpeg', 'products', 'image/jpeg', 256846, 800, 800, '/uploads/products/23.28.33 (1).jpeg', NULL, 'local', 'products/23.28.33 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0056', NULL, '23.28.33 (2).jpeg', 'products', 'products/23.28.33 (2).jpeg', 'products', 'image/jpeg', 269693, 800, 800, '/uploads/products/23.28.33 (2).jpeg', NULL, 'local', 'products/23.28.33 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0057', NULL, '23.28.33 (3).jpeg', 'products', 'products/23.28.33 (3).jpeg', 'products', 'image/jpeg', 291125, 800, 800, '/uploads/products/23.28.33 (3).jpeg', NULL, 'local', 'products/23.28.33 (3).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0058', NULL, '23.28.33.jpeg', 'products', 'products/23.28.33.jpeg', 'products', 'image/jpeg', 278988, 800, 800, '/uploads/products/23.28.33.jpeg', NULL, 'local', 'products/23.28.33.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0059', NULL, '23.28.34 (1).jpeg', 'products', 'products/23.28.34 (1).jpeg', 'products', 'image/jpeg', 228035, 800, 800, '/uploads/products/23.28.34 (1).jpeg', NULL, 'local', 'products/23.28.34 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0060', NULL, '23.28.34 (2).jpeg', 'products', 'products/23.28.34 (2).jpeg', 'products', 'image/jpeg', 214992, 800, 800, '/uploads/products/23.28.34 (2).jpeg', NULL, 'local', 'products/23.28.34 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0061', NULL, '23.28.34 (3).jpeg', 'products', 'products/23.28.34 (3).jpeg', 'products', 'image/jpeg', 487776, 800, 800, '/uploads/products/23.28.34 (3).jpeg', NULL, 'local', 'products/23.28.34 (3).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0062', NULL, '23.28.34.jpeg', 'products', 'products/23.28.34.jpeg', 'products', 'image/jpeg', 241750, 800, 800, '/uploads/products/23.28.34.jpeg', NULL, 'local', 'products/23.28.34.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0063', NULL, '23.28.35 (1).jpeg', 'products', 'products/23.28.35 (1).jpeg', 'products', 'image/jpeg', 408205, 800, 800, '/uploads/products/23.28.35 (1).jpeg', NULL, 'local', 'products/23.28.35 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0064', NULL, '23.28.35 (2).jpeg', 'products', 'products/23.28.35 (2).jpeg', 'products', 'image/jpeg', 499962, 800, 800, '/uploads/products/23.28.35 (2).jpeg', NULL, 'local', 'products/23.28.35 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0065', NULL, '23.28.35 (3).jpeg', 'products', 'products/23.28.35 (3).jpeg', 'products', 'image/jpeg', 319469, 800, 800, '/uploads/products/23.28.35 (3).jpeg', NULL, 'local', 'products/23.28.35 (3).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0066', NULL, '23.28.35 (4).jpeg', 'products', 'products/23.28.35 (4).jpeg', 'products', 'image/jpeg', 340682, 800, 800, '/uploads/products/23.28.35 (4).jpeg', NULL, 'local', 'products/23.28.35 (4).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0067', NULL, '23.28.35.jpeg', 'products', 'products/23.28.35.jpeg', 'products', 'image/jpeg', 401240, 800, 800, '/uploads/products/23.28.35.jpeg', NULL, 'local', 'products/23.28.35.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0068', NULL, '23.28.36 (1).jpeg', 'products', 'products/23.28.36 (1).jpeg', 'products', 'image/jpeg', 319164, 800, 800, '/uploads/products/23.28.36 (1).jpeg', NULL, 'local', 'products/23.28.36 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0069', NULL, '23.28.36 (2).jpeg', 'products', 'products/23.28.36 (2).jpeg', 'products', 'image/jpeg', 282867, 800, 800, '/uploads/products/23.28.36 (2).jpeg', NULL, 'local', 'products/23.28.36 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0070', NULL, '23.28.36 (3).jpeg', 'products', 'products/23.28.36 (3).jpeg', 'products', 'image/jpeg', 297433, 800, 800, '/uploads/products/23.28.36 (3).jpeg', NULL, 'local', 'products/23.28.36 (3).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0071', NULL, '23.28.36 (4).jpeg', 'products', 'products/23.28.36 (4).jpeg', 'products', 'image/jpeg', 424145, 800, 800, '/uploads/products/23.28.36 (4).jpeg', NULL, 'local', 'products/23.28.36 (4).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0072', NULL, '23.28.36.jpeg', 'products', 'products/23.28.36.jpeg', 'products', 'image/jpeg', 394564, 800, 800, '/uploads/products/23.28.36.jpeg', NULL, 'local', 'products/23.28.36.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0073', NULL, '23.28.37 (1).jpeg', 'products', 'products/23.28.37 (1).jpeg', 'products', 'image/jpeg', 232315, 800, 800, '/uploads/products/23.28.37 (1).jpeg', NULL, 'local', 'products/23.28.37 (1).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0074', NULL, '23.28.37 (2).jpeg', 'products', 'products/23.28.37 (2).jpeg', 'products', 'image/jpeg', 390691, 800, 800, '/uploads/products/23.28.37 (2).jpeg', NULL, 'local', 'products/23.28.37 (2).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0075', NULL, '23.28.37 (3).jpeg', 'products', 'products/23.28.37 (3).jpeg', 'products', 'image/jpeg', 367278, 800, 800, '/uploads/products/23.28.37 (3).jpeg', NULL, 'local', 'products/23.28.37 (3).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0076', NULL, '23.28.37 (4).jpeg', 'products', 'products/23.28.37 (4).jpeg', 'products', 'image/jpeg', 214149, 800, 800, '/uploads/products/23.28.37 (4).jpeg', NULL, 'local', 'products/23.28.37 (4).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0077', NULL, '23.28.37 (5).jpeg', 'products', 'products/23.28.37 (5).jpeg', 'products', 'image/jpeg', 252915, 800, 800, '/uploads/products/23.28.37 (5).jpeg', NULL, 'local', 'products/23.28.37 (5).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0078', NULL, '23.28.37 (6).jpeg', 'products', 'products/23.28.37 (6).jpeg', 'products', 'image/jpeg', 250258, 800, 800, '/uploads/products/23.28.37 (6).jpeg', NULL, 'local', 'products/23.28.37 (6).jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-prd-img-0079', NULL, '23.28.37.jpeg', 'products', 'products/23.28.37.jpeg', 'products', 'image/jpeg', 411933, 800, 800, '/uploads/products/23.28.37.jpeg', NULL, 'local', 'products/23.28.37.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  url = VALUES(url),
  size = VALUES(size),
  updated_at = NOW();

-- =========================
-- NEWS IMAGES
-- =========================
INSERT INTO `storage_assets`
(`id`, `user_id`, `name`, `bucket`, `path`, `folder`, `mime`, `size`, `width`, `height`, `url`, `hash`, `provider`, `provider_public_id`, `provider_resource_type`, `provider_format`, `provider_version`, `etag`, `metadata`, `created_at`, `updated_at`)
VALUES
  ('bf-news-img-0001', NULL, 'bugem.jpeg',  'news', 'news/bugem.jpeg',  'news', 'image/jpeg', 321046, 1200, 800, '/uploads/news/bugem.jpeg',  NULL, 'local', 'news/bugem.jpeg',  'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0002', NULL, 'bugem2.jpeg', 'news', 'news/bugem2.jpeg', 'news', 'image/jpeg', 360066, 1200, 800, '/uploads/news/bugem2.jpeg', NULL, 'local', 'news/bugem2.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0003', NULL, 'aksu.jpeg',   'news', 'news/aksu.jpeg',   'news', 'image/jpeg', 316171, 1200, 800, '/uploads/news/aksu.jpeg',   NULL, 'local', 'news/aksu.jpeg',   'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0004', NULL, 'aksu2.jpeg',  'news', 'news/aksu2.jpeg',  'news', 'image/jpeg', 170888, 1200, 800, '/uploads/news/aksu2.jpeg',  NULL, 'local', 'news/aksu2.jpeg',  'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0005', NULL, 'aksu3.jpeg',  'news', 'news/aksu3.jpeg',  'news', 'image/jpeg', 273223, 1200, 800, '/uploads/news/aksu3.jpeg',  NULL, 'local', 'news/aksu3.jpeg',  'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0006', NULL, 'aksu4.jpeg',  'news', 'news/aksu4.jpeg',  'news', 'image/jpeg', 312237, 1200, 800, '/uploads/news/aksu4.jpeg',  NULL, 'local', 'news/aksu4.jpeg',  'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0007', NULL, 'aksu5.jpeg',  'news', 'news/aksu5.jpeg',  'news', 'image/jpeg', 281663, 1200, 800, '/uploads/news/aksu5.jpeg',  NULL, 'local', 'news/aksu5.jpeg',  'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0008', NULL, 'samsun.jpeg',  'news', 'news/samsun.jpeg',  'news', 'image/jpeg', 507283, 1200, 800, '/uploads/news/samsun.jpeg',  NULL, 'local', 'news/samsun.jpeg',  'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0009', NULL, 'samsun2.jpeg', 'news', 'news/samsun2.jpeg', 'news', 'image/jpeg', 217424, 1200, 800, '/uploads/news/samsun2.jpeg', NULL, 'local', 'news/samsun2.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0010', NULL, 'samsun3.jpeg', 'news', 'news/samsun3.jpeg', 'news', 'image/jpeg', 686649, 1200, 800, '/uploads/news/samsun3.jpeg', NULL, 'local', 'news/samsun3.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0011', NULL, 'samsun4.jpeg', 'news', 'news/samsun4.jpeg', 'news', 'image/jpeg', 379621, 1200, 800, '/uploads/news/samsun4.jpeg', NULL, 'local', 'news/samsun4.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0012', NULL, 'samsun5.jpeg', 'news', 'news/samsun5.jpeg', 'news', 'image/jpeg', 537420, 1200, 800, '/uploads/news/samsun5.jpeg', NULL, 'local', 'news/samsun5.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0013', NULL, 'samsun6.jpeg', 'news', 'news/samsun6.jpeg', 'news', 'image/jpeg', 241424, 1200, 800, '/uploads/news/samsun6.jpeg', NULL, 'local', 'news/samsun6.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0014', NULL, 'samsun7.jpeg', 'news', 'news/samsun7.jpeg', 'news', 'image/jpeg', 287820, 1200, 800, '/uploads/news/samsun7.jpeg', NULL, 'local', 'news/samsun7.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0015', NULL, 'samsun8.jpeg', 'news', 'news/samsun8.jpeg', 'news', 'image/jpeg', 503636, 1200, 800, '/uploads/news/samsun8.jpeg', NULL, 'local', 'news/samsun8.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0016', NULL, 'aksuj.jpeg',  'news', 'news/aksuj.jpeg',  'news', 'image/jpeg', 537420, 1200, 800, '/uploads/news/aksuj.jpeg',  NULL, 'local', 'news/aksuj.jpeg',  'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0017', NULL, 'aksuj2.jpeg', 'news', 'news/aksuj2.jpeg', 'news', 'image/jpeg', 241424, 1200, 800, '/uploads/news/aksuj2.jpeg', NULL, 'local', 'news/aksuj2.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-news-img-0018', NULL, 'aksuj3.jpeg', 'news', 'news/aksuj3.jpeg', 'news', 'image/jpeg', 287820, 1200, 800, '/uploads/news/aksuj3.jpeg', NULL, 'local', 'news/aksuj3.jpeg', 'image', 'jpg', NULL, NULL, '{}', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  url = VALUES(url),
  size = VALUES(size),
  updated_at = NOW();

-- =========================
-- BRAND REFERENCES (is birligi firma logolari)
-- =========================
INSERT INTO `storage_assets`
(`id`, `user_id`, `name`, `bucket`, `path`, `folder`, `mime`, `size`, `width`, `height`, `url`, `hash`, `provider`, `provider_public_id`, `provider_resource_type`, `provider_format`, `provider_version`, `etag`, `metadata`, `created_at`, `updated_at`)
VALUES
  ('bf-brand-img-0001', NULL, 'enzazaden.jpg',              'brand_references', 'brand_references/enzazaden.jpg',              'brand_references', 'image/jpeg', 24613, NULL, NULL, '/uploads/brand_references/enzazaden.jpg',              NULL, 'local', 'brand_references/enzazaden.jpg',              'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-brand-img-0002', NULL, 'rijkzwaan.jpg',              'brand_references', 'brand_references/rijkzwaan.jpg',              'brand_references', 'image/jpeg', 23825, NULL, NULL, '/uploads/brand_references/rijkzwaan.jpg',              NULL, 'local', 'brand_references/rijkzwaan.jpg',              'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-brand-img-0003', NULL, 'seminis.jpg',                'brand_references', 'brand_references/seminis.jpg',                'brand_references', 'image/jpeg', 39834, NULL, NULL, '/uploads/brand_references/seminis.jpg',                NULL, 'local', 'brand_references/seminis.jpg',                'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-brand-img-0004', NULL, 'sakata.png',                 'brand_references', 'brand_references/sakata.png',                 'brand_references', 'image/png',  54667,  750, 215, '/uploads/brand_references/sakata.png',                 NULL, 'local', 'brand_references/sakata.png',                 'image', 'png', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-brand-img-0005', NULL, 'nunhems.png',                'brand_references', 'brand_references/nunhems.png',                'brand_references', 'image/png',   8882,  253, 199, '/uploads/brand_references/nunhems.png',                NULL, 'local', 'brand_references/nunhems.png',                'image', 'png', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-brand-img-0006', NULL, 'hmclause.png',               'brand_references', 'brand_references/hmclause.png',               'brand_references', 'image/png',  27298, 2000, 571, '/uploads/brand_references/hmclause.png',               NULL, 'local', 'brand_references/hmclause.png',               'image', 'png', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-brand-img-0007', NULL, 'genetika.png',               'brand_references', 'brand_references/genetika.png',               'brand_references', 'image/png',   2076,  225, 225, '/uploads/brand_references/genetika.png',               NULL, 'local', 'brand_references/genetika.png',               'image', 'png', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-brand-img-0008', NULL, 'yukseltohum.jpg',            'brand_references', 'brand_references/yukseltohum.jpg',            'brand_references', 'image/jpeg', 86327, NULL, NULL, '/uploads/brand_references/yukseltohum.jpg',            NULL, 'local', 'brand_references/yukseltohum.jpg',            'image', 'jpg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-brand-img-0009', NULL, 'anamas.jpeg',                'brand_references', 'brand_references/anamas.jpeg',                'brand_references', 'image/jpeg',  8213, NULL, NULL, '/uploads/brand_references/anamas.jpeg',                NULL, 'local', 'brand_references/anamas.jpeg',                'image', 'jpeg', NULL, NULL, '{}', NOW(), NOW()),
  ('bf-brand-img-0010', NULL, 'vistaseed_logo_black.png',   'brand_references', 'brand_references/vistaseed_logo_black.png',   'brand_references', 'image/png',  38607, 2014, 494, '/uploads/brand_references/vistaseed_logo_black.png',   NULL, 'local', 'brand_references/vistaseed_logo_black.png',   'image', 'png',  NULL, NULL, '{}', NOW(), NOW()),
  ('bf-brand-img-0011', NULL, 'vistaseeds.jpeg',            'brand_references', 'brand_references/vistaseeds.jpeg',            'brand_references', 'image/jpeg', 33281,  992, 581, '/uploads/brand_references/vistaseeds.jpeg',            NULL, 'local', 'brand_references/vistaseeds.jpeg',            'image', 'jpeg', NULL, NULL, '{}', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  url = VALUES(url),
  size = VALUES(size),
  width = VALUES(width),
  height = VALUES(height),
  updated_at = NOW();

-- =========================
-- INVENTORY SEED PACKAGE IMAGES
-- =========================
INSERT INTO `storage_assets`
(`id`, `user_id`, `name`, `bucket`, `path`, `folder`, `mime`, `size`, `width`, `height`, `url`, `hash`, `provider`, `provider_public_id`, `provider_resource_type`, `provider_format`, `provider_version`, `etag`, `metadata`, `created_at`, `updated_at`)
VALUES
  ('bf-inv-seed-img-0001', NULL, 'urun-01-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-01-arka.jpg', 'inventory-seeds', 'image/jpeg', 722119, 1404, 1871, '/uploads/inventory-seeds/urun-01-arka.jpg', NULL, 'local', 'inventory-seeds/urun-01-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "01", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0002', NULL, 'urun-01-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-01-on.jpg', 'inventory-seeds', 'image/jpeg', 659748, 1404, 1871, '/uploads/inventory-seeds/urun-01-on.jpg', NULL, 'local', 'inventory-seeds/urun-01-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "01", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0003', NULL, 'urun-02-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-02-arka.jpg', 'inventory-seeds', 'image/jpeg', 623691, 1404, 1871, '/uploads/inventory-seeds/urun-02-arka.jpg', NULL, 'local', 'inventory-seeds/urun-02-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "02", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0004', NULL, 'urun-02-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-02-on.jpg', 'inventory-seeds', 'image/jpeg', 536020, 1404, 1871, '/uploads/inventory-seeds/urun-02-on.jpg', NULL, 'local', 'inventory-seeds/urun-02-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "02", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0005', NULL, 'urun-03-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-03-arka.jpg', 'inventory-seeds', 'image/jpeg', 639165, 1404, 1871, '/uploads/inventory-seeds/urun-03-arka.jpg', NULL, 'local', 'inventory-seeds/urun-03-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "03", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0006', NULL, 'urun-03-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-03-on.jpg', 'inventory-seeds', 'image/jpeg', 634537, 1404, 1871, '/uploads/inventory-seeds/urun-03-on.jpg', NULL, 'local', 'inventory-seeds/urun-03-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "03", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0007', NULL, 'urun-04-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-04-arka.jpg', 'inventory-seeds', 'image/jpeg', 853245, 1404, 1871, '/uploads/inventory-seeds/urun-04-arka.jpg', NULL, 'local', 'inventory-seeds/urun-04-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "04", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0008', NULL, 'urun-04-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-04-on.jpg', 'inventory-seeds', 'image/jpeg', 646029, 1404, 1871, '/uploads/inventory-seeds/urun-04-on.jpg', NULL, 'local', 'inventory-seeds/urun-04-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "04", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0009', NULL, 'urun-05-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-05-arka.jpg', 'inventory-seeds', 'image/jpeg', 670702, 1404, 1871, '/uploads/inventory-seeds/urun-05-arka.jpg', NULL, 'local', 'inventory-seeds/urun-05-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "05", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0010', NULL, 'urun-05-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-05-on.jpg', 'inventory-seeds', 'image/jpeg', 514414, 1404, 1871, '/uploads/inventory-seeds/urun-05-on.jpg', NULL, 'local', 'inventory-seeds/urun-05-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "05", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0011', NULL, 'urun-06-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-06-arka.jpg', 'inventory-seeds', 'image/jpeg', 904677, 1404, 1871, '/uploads/inventory-seeds/urun-06-arka.jpg', NULL, 'local', 'inventory-seeds/urun-06-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "06", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0012', NULL, 'urun-06-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-06-on.jpg', 'inventory-seeds', 'image/jpeg', 695276, 1404, 1871, '/uploads/inventory-seeds/urun-06-on.jpg', NULL, 'local', 'inventory-seeds/urun-06-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "06", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0013', NULL, 'urun-07-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-07-arka.jpg', 'inventory-seeds', 'image/jpeg', 535457, 1404, 1871, '/uploads/inventory-seeds/urun-07-arka.jpg', NULL, 'local', 'inventory-seeds/urun-07-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "07", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0014', NULL, 'urun-07-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-07-on.jpg', 'inventory-seeds', 'image/jpeg', 455720, 1404, 1871, '/uploads/inventory-seeds/urun-07-on.jpg', NULL, 'local', 'inventory-seeds/urun-07-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "07", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0015', NULL, 'urun-08-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-08-arka.jpg', 'inventory-seeds', 'image/jpeg', 545367, 1404, 1871, '/uploads/inventory-seeds/urun-08-arka.jpg', NULL, 'local', 'inventory-seeds/urun-08-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "08", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0016', NULL, 'urun-08-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-08-on.jpg', 'inventory-seeds', 'image/jpeg', 539307, 1404, 1871, '/uploads/inventory-seeds/urun-08-on.jpg', NULL, 'local', 'inventory-seeds/urun-08-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "08", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0017', NULL, 'urun-09-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-09-arka.jpg', 'inventory-seeds', 'image/jpeg', 706271, 1404, 1871, '/uploads/inventory-seeds/urun-09-arka.jpg', NULL, 'local', 'inventory-seeds/urun-09-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "09", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0018', NULL, 'urun-09-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-09-on.jpg', 'inventory-seeds', 'image/jpeg', 587347, 1404, 1871, '/uploads/inventory-seeds/urun-09-on.jpg', NULL, 'local', 'inventory-seeds/urun-09-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "09", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0019', NULL, 'urun-10-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-10-arka.jpg', 'inventory-seeds', 'image/jpeg', 633847, 1404, 1871, '/uploads/inventory-seeds/urun-10-arka.jpg', NULL, 'local', 'inventory-seeds/urun-10-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "10", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0020', NULL, 'urun-10-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-10-on.jpg', 'inventory-seeds', 'image/jpeg', 590090, 1404, 1871, '/uploads/inventory-seeds/urun-10-on.jpg', NULL, 'local', 'inventory-seeds/urun-10-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "10", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0021', NULL, 'urun-11-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-11-arka.jpg', 'inventory-seeds', 'image/jpeg', 747116, 1404, 1871, '/uploads/inventory-seeds/urun-11-arka.jpg', NULL, 'local', 'inventory-seeds/urun-11-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "11", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0022', NULL, 'urun-11-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-11-on.jpg', 'inventory-seeds', 'image/jpeg', 632422, 1404, 1871, '/uploads/inventory-seeds/urun-11-on.jpg', NULL, 'local', 'inventory-seeds/urun-11-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "11", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0023', NULL, 'urun-12-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-12-arka.jpg', 'inventory-seeds', 'image/jpeg', 625013, 1404, 1871, '/uploads/inventory-seeds/urun-12-arka.jpg', NULL, 'local', 'inventory-seeds/urun-12-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "12", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0024', NULL, 'urun-12-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-12-on.jpg', 'inventory-seeds', 'image/jpeg', 503984, 1404, 1871, '/uploads/inventory-seeds/urun-12-on.jpg', NULL, 'local', 'inventory-seeds/urun-12-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "12", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0025', NULL, 'urun-13-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-13-arka.jpg', 'inventory-seeds', 'image/jpeg', 638853, 1404, 1871, '/uploads/inventory-seeds/urun-13-arka.jpg', NULL, 'local', 'inventory-seeds/urun-13-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "13", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0026', NULL, 'urun-13-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-13-on.jpg', 'inventory-seeds', 'image/jpeg', 582673, 1404, 1871, '/uploads/inventory-seeds/urun-13-on.jpg', NULL, 'local', 'inventory-seeds/urun-13-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "13", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0027', NULL, 'urun-14-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-14-arka.jpg', 'inventory-seeds', 'image/jpeg', 647711, 1404, 1871, '/uploads/inventory-seeds/urun-14-arka.jpg', NULL, 'local', 'inventory-seeds/urun-14-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "14", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0028', NULL, 'urun-14-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-14-on.jpg', 'inventory-seeds', 'image/jpeg', 618683, 1404, 1871, '/uploads/inventory-seeds/urun-14-on.jpg', NULL, 'local', 'inventory-seeds/urun-14-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "14", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0029', NULL, 'urun-15-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-15-arka.jpg', 'inventory-seeds', 'image/jpeg', 738306, 1404, 1871, '/uploads/inventory-seeds/urun-15-arka.jpg', NULL, 'local', 'inventory-seeds/urun-15-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "15", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0030', NULL, 'urun-15-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-15-on.jpg', 'inventory-seeds', 'image/jpeg', 562358, 1404, 1871, '/uploads/inventory-seeds/urun-15-on.jpg', NULL, 'local', 'inventory-seeds/urun-15-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "15", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0031', NULL, 'urun-16-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-16-arka.jpg', 'inventory-seeds', 'image/jpeg', 672837, 1404, 1871, '/uploads/inventory-seeds/urun-16-arka.jpg', NULL, 'local', 'inventory-seeds/urun-16-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "16", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0032', NULL, 'urun-16-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-16-on.jpg', 'inventory-seeds', 'image/jpeg', 522495, 1404, 1871, '/uploads/inventory-seeds/urun-16-on.jpg', NULL, 'local', 'inventory-seeds/urun-16-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "16", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0033', NULL, 'urun-17-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-17-arka.jpg', 'inventory-seeds', 'image/jpeg', 802551, 1404, 1871, '/uploads/inventory-seeds/urun-17-arka.jpg', NULL, 'local', 'inventory-seeds/urun-17-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "17", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0034', NULL, 'urun-17-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-17-on.jpg', 'inventory-seeds', 'image/jpeg', 728352, 1404, 1871, '/uploads/inventory-seeds/urun-17-on.jpg', NULL, 'local', 'inventory-seeds/urun-17-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "17", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0035', NULL, 'urun-18-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-18-arka.jpg', 'inventory-seeds', 'image/jpeg', 735421, 1404, 1871, '/uploads/inventory-seeds/urun-18-arka.jpg', NULL, 'local', 'inventory-seeds/urun-18-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "18", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0036', NULL, 'urun-18-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-18-on.jpg', 'inventory-seeds', 'image/jpeg', 632972, 1404, 1871, '/uploads/inventory-seeds/urun-18-on.jpg', NULL, 'local', 'inventory-seeds/urun-18-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "18", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0037', NULL, 'urun-19-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-19-arka.jpg', 'inventory-seeds', 'image/jpeg', 661499, 1404, 1871, '/uploads/inventory-seeds/urun-19-arka.jpg', NULL, 'local', 'inventory-seeds/urun-19-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "19", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0038', NULL, 'urun-19-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-19-on.jpg', 'inventory-seeds', 'image/jpeg', 647107, 1404, 1871, '/uploads/inventory-seeds/urun-19-on.jpg', NULL, 'local', 'inventory-seeds/urun-19-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "19", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0039', NULL, 'urun-20-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-20-arka.jpg', 'inventory-seeds', 'image/jpeg', 695414, 1404, 1871, '/uploads/inventory-seeds/urun-20-arka.jpg', NULL, 'local', 'inventory-seeds/urun-20-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "20", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0040', NULL, 'urun-20-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-20-on.jpg', 'inventory-seeds', 'image/jpeg', 607926, 1404, 1871, '/uploads/inventory-seeds/urun-20-on.jpg', NULL, 'local', 'inventory-seeds/urun-20-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "20", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0041', NULL, 'urun-21-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-21-arka.jpg', 'inventory-seeds', 'image/jpeg', 718118, 1404, 1871, '/uploads/inventory-seeds/urun-21-arka.jpg', NULL, 'local', 'inventory-seeds/urun-21-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "21", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0042', NULL, 'urun-21-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-21-on.jpg', 'inventory-seeds', 'image/jpeg', 658001, 1404, 1871, '/uploads/inventory-seeds/urun-21-on.jpg', NULL, 'local', 'inventory-seeds/urun-21-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "21", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0043', NULL, 'urun-22-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-22-arka.jpg', 'inventory-seeds', 'image/jpeg', 661426, 1404, 1871, '/uploads/inventory-seeds/urun-22-arka.jpg', NULL, 'local', 'inventory-seeds/urun-22-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "22", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0044', NULL, 'urun-22-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-22-on.jpg', 'inventory-seeds', 'image/jpeg', 643202, 1404, 1871, '/uploads/inventory-seeds/urun-22-on.jpg', NULL, 'local', 'inventory-seeds/urun-22-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "22", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0045', NULL, 'urun-23-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-23-arka.jpg', 'inventory-seeds', 'image/jpeg', 687524, 1404, 1871, '/uploads/inventory-seeds/urun-23-arka.jpg', NULL, 'local', 'inventory-seeds/urun-23-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "23", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0046', NULL, 'urun-23-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-23-on.jpg', 'inventory-seeds', 'image/jpeg', 635820, 1404, 1871, '/uploads/inventory-seeds/urun-23-on.jpg', NULL, 'local', 'inventory-seeds/urun-23-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "23", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0047', NULL, 'urun-24-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-24-arka.jpg', 'inventory-seeds', 'image/jpeg', 612593, 1404, 1871, '/uploads/inventory-seeds/urun-24-arka.jpg', NULL, 'local', 'inventory-seeds/urun-24-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "24", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0048', NULL, 'urun-24-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-24-on.jpg', 'inventory-seeds', 'image/jpeg', 480904, 1404, 1871, '/uploads/inventory-seeds/urun-24-on.jpg', NULL, 'local', 'inventory-seeds/urun-24-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "24", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0049', NULL, 'urun-25-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-25-arka.jpg', 'inventory-seeds', 'image/jpeg', 815549, 1404, 1871, '/uploads/inventory-seeds/urun-25-arka.jpg', NULL, 'local', 'inventory-seeds/urun-25-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "25", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0050', NULL, 'urun-25-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-25-on.jpg', 'inventory-seeds', 'image/jpeg', 753680, 1404, 1871, '/uploads/inventory-seeds/urun-25-on.jpg', NULL, 'local', 'inventory-seeds/urun-25-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "25", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0051', NULL, 'urun-26-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-26-arka.jpg', 'inventory-seeds', 'image/jpeg', 468916, 1404, 1871, '/uploads/inventory-seeds/urun-26-arka.jpg', NULL, 'local', 'inventory-seeds/urun-26-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "26", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0052', NULL, 'urun-26-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-26-on.jpg', 'inventory-seeds', 'image/jpeg', 743475, 1404, 1871, '/uploads/inventory-seeds/urun-26-on.jpg', NULL, 'local', 'inventory-seeds/urun-26-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "26", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0053', NULL, 'urun-27-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-27-arka.jpg', 'inventory-seeds', 'image/jpeg', 830608, 1404, 1871, '/uploads/inventory-seeds/urun-27-arka.jpg', NULL, 'local', 'inventory-seeds/urun-27-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "27", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0054', NULL, 'urun-27-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-27-on.jpg', 'inventory-seeds', 'image/jpeg', 770611, 1404, 1871, '/uploads/inventory-seeds/urun-27-on.jpg', NULL, 'local', 'inventory-seeds/urun-27-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "27", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0055', NULL, 'urun-28-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-28-arka.jpg', 'inventory-seeds', 'image/jpeg', 669059, 1404, 1871, '/uploads/inventory-seeds/urun-28-arka.jpg', NULL, 'local', 'inventory-seeds/urun-28-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "28", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0056', NULL, 'urun-28-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-28-on.jpg', 'inventory-seeds', 'image/jpeg', 601048, 1404, 1871, '/uploads/inventory-seeds/urun-28-on.jpg', NULL, 'local', 'inventory-seeds/urun-28-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "28", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0057', NULL, 'urun-29-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-29-arka.jpg', 'inventory-seeds', 'image/jpeg', 696523, 1404, 1871, '/uploads/inventory-seeds/urun-29-arka.jpg', NULL, 'local', 'inventory-seeds/urun-29-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "29", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0058', NULL, 'urun-29-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-29-on.jpg', 'inventory-seeds', 'image/jpeg', 728760, 1404, 1871, '/uploads/inventory-seeds/urun-29-on.jpg', NULL, 'local', 'inventory-seeds/urun-29-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "29", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0059', NULL, 'urun-30-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-30-arka.jpg', 'inventory-seeds', 'image/jpeg', 912788, 1404, 1871, '/uploads/inventory-seeds/urun-30-arka.jpg', NULL, 'local', 'inventory-seeds/urun-30-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "30", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0060', NULL, 'urun-30-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-30-on.jpg', 'inventory-seeds', 'image/jpeg', 770357, 1404, 1871, '/uploads/inventory-seeds/urun-30-on.jpg', NULL, 'local', 'inventory-seeds/urun-30-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "30", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0061', NULL, 'urun-31-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-31-arka.jpg', 'inventory-seeds', 'image/jpeg', 792408, 1404, 1871, '/uploads/inventory-seeds/urun-31-arka.jpg', NULL, 'local', 'inventory-seeds/urun-31-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "31", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0062', NULL, 'urun-31-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-31-on.jpg', 'inventory-seeds', 'image/jpeg', 652068, 1404, 1871, '/uploads/inventory-seeds/urun-31-on.jpg', NULL, 'local', 'inventory-seeds/urun-31-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "31", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0063', NULL, 'urun-32-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-32-arka.jpg', 'inventory-seeds', 'image/jpeg', 634309, 1404, 1871, '/uploads/inventory-seeds/urun-32-arka.jpg', NULL, 'local', 'inventory-seeds/urun-32-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "32", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0064', NULL, 'urun-32-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-32-on.jpg', 'inventory-seeds', 'image/jpeg', 660943, 1404, 1871, '/uploads/inventory-seeds/urun-32-on.jpg', NULL, 'local', 'inventory-seeds/urun-32-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "32", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0065', NULL, 'urun-33-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-33-arka.jpg', 'inventory-seeds', 'image/jpeg', 667121, 1404, 1871, '/uploads/inventory-seeds/urun-33-arka.jpg', NULL, 'local', 'inventory-seeds/urun-33-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "33", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0066', NULL, 'urun-33-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-33-on.jpg', 'inventory-seeds', 'image/jpeg', 571048, 1404, 1871, '/uploads/inventory-seeds/urun-33-on.jpg', NULL, 'local', 'inventory-seeds/urun-33-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "33", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0067', NULL, 'urun-34-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-34-arka.jpg', 'inventory-seeds', 'image/jpeg', 761653, 1404, 1871, '/uploads/inventory-seeds/urun-34-arka.jpg', NULL, 'local', 'inventory-seeds/urun-34-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "34", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0068', NULL, 'urun-34-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-34-on.jpg', 'inventory-seeds', 'image/jpeg', 595927, 1404, 1871, '/uploads/inventory-seeds/urun-34-on.jpg', NULL, 'local', 'inventory-seeds/urun-34-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "34", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0069', NULL, 'urun-35-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-35-arka.jpg', 'inventory-seeds', 'image/jpeg', 872363, 1404, 1871, '/uploads/inventory-seeds/urun-35-arka.jpg', NULL, 'local', 'inventory-seeds/urun-35-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "35", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0070', NULL, 'urun-35-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-35-on.jpg', 'inventory-seeds', 'image/jpeg', 721592, 1404, 1871, '/uploads/inventory-seeds/urun-35-on.jpg', NULL, 'local', 'inventory-seeds/urun-35-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "35", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0071', NULL, 'urun-36-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-36-arka.jpg', 'inventory-seeds', 'image/jpeg', 862329, 1404, 1871, '/uploads/inventory-seeds/urun-36-arka.jpg', NULL, 'local', 'inventory-seeds/urun-36-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "36", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0072', NULL, 'urun-36-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-36-on.jpg', 'inventory-seeds', 'image/jpeg', 621768, 1404, 1871, '/uploads/inventory-seeds/urun-36-on.jpg', NULL, 'local', 'inventory-seeds/urun-36-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "36", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0073', NULL, 'urun-37-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-37-arka.jpg', 'inventory-seeds', 'image/jpeg', 577873, 1404, 1871, '/uploads/inventory-seeds/urun-37-arka.jpg', NULL, 'local', 'inventory-seeds/urun-37-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "37", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0074', NULL, 'urun-37-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-37-on.jpg', 'inventory-seeds', 'image/jpeg', 599861, 1404, 1871, '/uploads/inventory-seeds/urun-37-on.jpg', NULL, 'local', 'inventory-seeds/urun-37-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "37", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0075', NULL, 'urun-38-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-38-arka.jpg', 'inventory-seeds', 'image/jpeg', 523960, 1404, 1871, '/uploads/inventory-seeds/urun-38-arka.jpg', NULL, 'local', 'inventory-seeds/urun-38-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "38", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0076', NULL, 'urun-38-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-38-on.jpg', 'inventory-seeds', 'image/jpeg', 610662, 1404, 1871, '/uploads/inventory-seeds/urun-38-on.jpg', NULL, 'local', 'inventory-seeds/urun-38-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "38", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0077', NULL, 'urun-39-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-39-arka.jpg', 'inventory-seeds', 'image/jpeg', 636179, 1404, 1871, '/uploads/inventory-seeds/urun-39-arka.jpg', NULL, 'local', 'inventory-seeds/urun-39-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "39", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0078', NULL, 'urun-39-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-39-on.jpg', 'inventory-seeds', 'image/jpeg', 644433, 1404, 1871, '/uploads/inventory-seeds/urun-39-on.jpg', NULL, 'local', 'inventory-seeds/urun-39-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "39", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0079', NULL, 'urun-40-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-40-arka.jpg', 'inventory-seeds', 'image/jpeg', 505192, 1404, 1871, '/uploads/inventory-seeds/urun-40-arka.jpg', NULL, 'local', 'inventory-seeds/urun-40-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "40", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0080', NULL, 'urun-40-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-40-on.jpg', 'inventory-seeds', 'image/jpeg', 515864, 1404, 1871, '/uploads/inventory-seeds/urun-40-on.jpg', NULL, 'local', 'inventory-seeds/urun-40-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "40", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0081', NULL, 'urun-41-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-41-arka.jpg', 'inventory-seeds', 'image/jpeg', 714384, 1404, 1871, '/uploads/inventory-seeds/urun-41-arka.jpg', NULL, 'local', 'inventory-seeds/urun-41-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "41", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0082', NULL, 'urun-41-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-41-on.jpg', 'inventory-seeds', 'image/jpeg', 677023, 1404, 1871, '/uploads/inventory-seeds/urun-41-on.jpg', NULL, 'local', 'inventory-seeds/urun-41-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "41", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0083', NULL, 'urun-42-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-42-arka.jpg', 'inventory-seeds', 'image/jpeg', 849178, 1404, 1871, '/uploads/inventory-seeds/urun-42-arka.jpg', NULL, 'local', 'inventory-seeds/urun-42-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "42", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0084', NULL, 'urun-42-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-42-on.jpg', 'inventory-seeds', 'image/jpeg', 661628, 1404, 1871, '/uploads/inventory-seeds/urun-42-on.jpg', NULL, 'local', 'inventory-seeds/urun-42-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "42", "side": "front"}', NOW(), NOW()),
  ('bf-inv-seed-img-0085', NULL, 'urun-43-arka.jpg', 'inventory-seeds', 'inventory-seeds/urun-43-arka.jpg', 'inventory-seeds', 'image/jpeg', 680412, 1404, 1871, '/uploads/inventory-seeds/urun-43-arka.jpg', NULL, 'local', 'inventory-seeds/urun-43-arka.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "43", "side": "back"}', NOW(), NOW()),
  ('bf-inv-seed-img-0086', NULL, 'urun-43-on.jpg', 'inventory-seeds', 'inventory-seeds/urun-43-on.jpg', 'inventory-seeds', 'image/jpeg', 692070, 1404, 1871, '/uploads/inventory-seeds/urun-43-on.jpg', NULL, 'local', 'inventory-seeds/urun-43-on.jpg', 'image', 'jpg', NULL, NULL, '{"source": "whatsapp_inventory_seed_photos", "pair_no": "43", "side": "front"}', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  size = VALUES(size),
  width = VALUES(width),
  height = VALUES(height),
  url = VALUES(url),
  metadata = VALUES(metadata),
  updated_at = NOW();

COMMIT;
SET FOREIGN_KEY_CHECKS = 1;
